### ISSUE TITLE
Add an expand/collapse all button

### ISSUE THREAD

**Issue by edg2s** [joakin/group-phabricator-notifications#3]

**Comment by joakin** [comment]
Thanks for the contribution!

I've added a couple of changes on top, like moving the buttons to the header with the other buttons and adding them icons.

I've submitted the new version to the chrome store, but they have new rules now for the content matches on the manifest.json and they say that "Due to the Host Permission, your extension may require an in-depth review which will delay publishing. Learn how to resolve this issue".

On publishing they also mention: "Every extension is reviewed prior to publication, which can take several weeks." so, we'll see if or when it gets published. It is marked as 1.4 there.

Have a good one!

**Comment by joakin** [comment]
@20after4 I think you were maintaining a firefox version as well? You may be interested in the latest commits that add a new expand-all/collapse-all feature.

**Comment by edg2s** [comment]
Looks great, thanks!
